--- 
title: "Introdução a Superfície de Volatilidade"
author: "Rafael Felipe Bressan"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [library.bib]
biblio-style: apalike
link-citations: yes
github-repo: rfbressan/vol_surface_gitbook
description: "Projeto de pequeno gitbook sobre superfície de volatilidade para o Clube de Finanças ESAG."
---

# Prefácio {-}

Este é um pequeno resumo, elaborado na forma de livro, sobre os estudos realizados pelo núcleo de derivativos e riscos do [Clube de finanças ESAG](https://clubedefinancas.com.br).

Os estudos realizados pelos membros do núcleo foram sendo apresentados na forma de artigos no blog do Clube. A partir destes artigos foi feita esta coletânea de forma a apresentar todo o conteúdo em local único para facilitar a assimilação dos membros futuros e leitores de nosso blog.

# Sobre os Autores {-}

## Rafael Felipe Bressan {-}

Formado em Engenharia de Controle e Automação Industrial pela UFSC e aluno de graduação do curso de Ciências Econômicas na UDESC/Esag. Membro do Clube de Finanças Esag e gerente do núcleo de pesquisa em riscos e derivativos. 

Se interessa por finanças quantitativas, modelagem e controle de riscos e desenvolveu, durante a elaboração deste livro, grande curiosidade sobre precificação de derivativos. Gosta de programar em [R](https://cran.r-project.org/), liguagem com a qual elaborou este próprio livro e está aprendendo [Python](https://www.python.org/).


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Verifies if needed packages are installed
pkgs_att <- c("tidyverse", 
              "tidyquant",
              "ggridges", 
              "ggthemes")
new.pkgs <- pkgs_att[!(pkgs_att %in% .packages(all.available = TRUE))]

# Installs new packages
if (length(new.pkgs)) install.packages(new.pkgs)

# Loads and attaches all needed packages
for (s in pkgs_att) {
  if (!library(s, character.only = TRUE, logical.return = TRUE)) 
    stop("Error loading packages.")
}
```
